version: "3.9"
services:
  windows:
    image: annihilator708/compile-juggernaut-windows
    build:
      context: .
      dockerfile: windows/windows.Dockerfile
      args:
        WINE_VERSION: wine-stable
    environment:
      - WINEARCH=win64
      - WINEDEBUG=fixme-all
      - WINEPREFIX=/wine
      - SPEC_FILENAME=main.spec
      - PYTHON_VERSION=3.9.9
      - PYINSTALLER_VERSION=5.3

  unix:
    image: annihilator708/compile-juggernaut-unix
    build:
      context: .
      dockerfile: unix/unix.Dockerfile
      args:
        PYTHON_VERSION: 3.9.9
        PYINSTALLER_VERSION: 5.3
    environment:
      - SPEC_FILENAME=main.spec
